In [1]:
import numpy as np
np.__version__

'1.18.1'

Создание массивов из списков

In [2]:
np.array([1, 2, 3, 4 ,5])

array([1, 2, 3, 4, 5])

In [3]:
# при несовпадении типов выполняется повышающее преобразование
np.array([1., 2, 3, 4 ,5])

array([1., 2., 3., 4., 5.])

In [4]:
# тип явно задается через dtype
np.array([1, 2, 3, 4 ,5], dtype='float32')

array([1., 2., 3., 4., 5.], dtype=float32)

In [8]:
# естественно многомерность
np.array([range(i, i + 4) for i in [1, 2, 3]])

array([[1, 2, 3, 4],
       [2, 3, 4, 5],
       [3, 4, 5, 6]])

Создание массивов

In [9]:
# инициализация нулями
np.zeros(10, dtype=int)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [10]:
# инициализация единицами
np.ones((3, 5), dtype=float)

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [11]:
# инициализация значением
np.full((3, 5), 3.14)

array([[3.14, 3.14, 3.14, 3.14, 3.14],
       [3.14, 3.14, 3.14, 3.14, 3.14],
       [3.14, 3.14, 3.14, 3.14, 3.14]])

In [12]:
# инициализация через генератор последовательности 0, 20 с шагом 2
np.arange(0, 20, 2)

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [13]:
# инициализируем, равномерно распределяя 5 значени в интервале 0, 1
np.linspace(0, 1, 5)

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

In [14]:
# заполним рандомными значениями от 0 до 3 массив 3х3
np.random.random((3, 3))

array([[0.63841362, 0.72525897, 0.21999544],
       [0.55492468, 0.60704344, 0.43193248],
       [0.66684441, 0.46966056, 0.63867997]])

In [15]:
# тоже самое, но нормальное распределение с медианой 0 и стандартным отклонением 1
np.random.normal(0, 1, (3, 3))

array([[-0.87665787, -1.68261312,  0.74867444],
       [ 0.17494943, -0.80968744, -0.33057308],
       [-0.83687806, -0.30913679,  1.65135659]])

In [16]:
# случайне целые числа из промежутка 3, 7
np.random.randint(3, 7, (3, 3))

array([[3, 4, 5],
       [5, 3, 4],
       [6, 3, 4]])

In [17]:
# единичная матрица
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [20]:
# инициализация массива числами, произвольно оказавшимися в случайных ячейках памяти
np.empty((3, 3))

array([[-0.87665787, -1.68261312,  0.74867444],
       [ 0.17494943, -0.80968744, -0.33057308],
       [-0.83687806, -0.30913679,  1.65135659]])

Типы данных в Numpy

| Data type	    | Description |
|---------------|-------------|
| ``bool_``     | Boolean (True or False) stored as a byte |
| ``int_``      | Default integer type (same as C ``long``; normally either ``int64`` or ``int32``)| 
| ``intc``      | Identical to C ``int`` (normally ``int32`` or ``int64``)| 
| ``intp``      | Integer used for indexing (same as C ``ssize_t``; normally either ``int32`` or ``int64``)| 
| ``int8``      | Byte (-128 to 127)| 
| ``int16``     | Integer (-32768 to 32767)|
| ``int32``     | Integer (-2147483648 to 2147483647)|
| ``int64``     | Integer (-9223372036854775808 to 9223372036854775807)| 
| ``uint8``     | Unsigned integer (0 to 255)| 
| ``uint16``    | Unsigned integer (0 to 65535)| 
| ``uint32``    | Unsigned integer (0 to 4294967295)| 
| ``uint64``    | Unsigned integer (0 to 18446744073709551615)| 
| ``float_``    | Shorthand for ``float64``.| 
| ``float16``   | Half precision float: sign bit, 5 bits exponent, 10 bits mantissa| 
| ``float32``   | Single precision float: sign bit, 8 bits exponent, 23 bits mantissa| 
| ``float64``   | Double precision float: sign bit, 11 bits exponent, 52 bits mantissa| 
| ``complex_``  | Shorthand for ``complex128``.| 
| ``complex64`` | Complex number, represented by two 32-bit floats| 
| ``complex128``| Complex number, represented by two 64-bit floats| 

Массивы

In [21]:
np.random.seed(0)
x1 = np.random.randint(10, size=6) # одномерный массив
x2 = np.random.randint(10, size=(3, 4)) # двумерный массив
x3 = np.random.randint(10, size=(3, 4, 5)) # трехмерный массив

In [24]:
# Атрибуты массивов
print('ndim(размерность масива): {0}\nshape(размер каждого измеренеия):\
{1}\nsize(общий размер массива): {2}'.format(x3.ndim, x3.shape, x3.size))

ndim(размерность масива): 3
shape(размер каждого измеренеия):(3, 4, 5)
size(общий размер массива): 60


In [25]:
print('dtype(тип данных): ', x3.dtype)

dtype(тип данных):  int64


In [26]:
print('itemsize:', x3.itemsize, 'bytes')

itemsize: 8 bytes


In [27]:
print('nbytes:', x3.nbytes, 'bytes')

nbytes: 480 bytes


In [28]:
x3.nbytes == x3.itemsize * x3.size

True