In [1]:
import numpy as np
np.__version__

'1.18.1'

Создание массивов из списков

In [2]:
np.array([1, 2, 3, 4 ,5])

array([1, 2, 3, 4, 5])

In [3]:
# при несовпадении типов выполняется повышающее преобразование
np.array([1., 2, 3, 4 ,5])

array([1., 2., 3., 4., 5.])

In [4]:
# тип явно задается через dtype
np.array([1, 2, 3, 4 ,5], dtype='float32')

array([1., 2., 3., 4., 5.], dtype=float32)

In [5]:
# естественно многомерность
np.array([range(i, i + 4) for i in [1, 2, 3]])

array([[1, 2, 3, 4],
       [2, 3, 4, 5],
       [3, 4, 5, 6]])

Создание массивов

In [6]:
# инициализация нулями
np.zeros(10, dtype=int)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [7]:
# инициализация единицами
np.ones((3, 5), dtype=float)

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [8]:
# инициализация значением
np.full((3, 5), 3.14)

array([[3.14, 3.14, 3.14, 3.14, 3.14],
       [3.14, 3.14, 3.14, 3.14, 3.14],
       [3.14, 3.14, 3.14, 3.14, 3.14]])

In [9]:
# инициализация через генератор последовательности 0, 20 с шагом 2
np.arange(0, 20, 2)

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [10]:
# инициализируем, равномерно распределяя 5 значени в интервале 0, 1
np.linspace(0, 1, 5)

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

In [11]:
# заполним рандомными значениями от 0 до 3 массив 3х3
np.random.random((3, 3))

array([[0.35351671, 0.67269856, 0.92653228],
       [0.14020542, 0.28577582, 0.88077124],
       [0.8751782 , 0.70425605, 0.56571391]])

In [12]:
# тоже самое, но нормальное распределение с медианой 0 и стандартным отклонением 1
np.random.normal(0, 1, (3, 3))

array([[ 0.98450673, -2.18333152, -0.3595023 ],
       [-1.60987697,  0.83084631, -1.58270847],
       [ 1.60457087,  0.14924135, -0.10024261]])

In [13]:
# случайне целые числа из промежутка 3, 7
np.random.randint(3, 7, (3, 3))

array([[4, 6, 3],
       [4, 6, 6],
       [5, 5, 6]])

In [14]:
# единичная матрица
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [15]:
# инициализация массива числами, произвольно оказавшимися в случайных ячейках памяти
np.empty((3, 3))

array([[ 0.98450673, -2.18333152, -0.3595023 ],
       [-1.60987697,  0.83084631, -1.58270847],
       [ 1.60457087,  0.14924135, -0.10024261]])

Типы данных в Numpy

| Data type	    | Description |
|---------------|-------------|
| ``bool_``     | Boolean (True or False) stored as a byte |
| ``int_``      | Default integer type (same as C ``long``; normally either ``int64`` or ``int32``)| 
| ``intc``      | Identical to C ``int`` (normally ``int32`` or ``int64``)| 
| ``intp``      | Integer used for indexing (same as C ``ssize_t``; normally either ``int32`` or ``int64``)| 
| ``int8``      | Byte (-128 to 127)| 
| ``int16``     | Integer (-32768 to 32767)|
| ``int32``     | Integer (-2147483648 to 2147483647)|
| ``int64``     | Integer (-9223372036854775808 to 9223372036854775807)| 
| ``uint8``     | Unsigned integer (0 to 255)| 
| ``uint16``    | Unsigned integer (0 to 65535)| 
| ``uint32``    | Unsigned integer (0 to 4294967295)| 
| ``uint64``    | Unsigned integer (0 to 18446744073709551615)| 
| ``float_``    | Shorthand for ``float64``.| 
| ``float16``   | Half precision float: sign bit, 5 bits exponent, 10 bits mantissa| 
| ``float32``   | Single precision float: sign bit, 8 bits exponent, 23 bits mantissa| 
| ``float64``   | Double precision float: sign bit, 11 bits exponent, 52 bits mantissa| 
| ``complex_``  | Shorthand for ``complex128``.| 
| ``complex64`` | Complex number, represented by two 32-bit floats| 
| ``complex128``| Complex number, represented by two 64-bit floats| 

Массивы

In [16]:
np.random.seed(0)
x1 = np.random.randint(10, size=6) # одномерный массив
x2 = np.random.randint(10, size=(3, 4)) # двумерный массив
x3 = np.random.randint(10, size=(3, 4, 5)) # трехмерный массив

In [17]:
# Атрибуты массивов
print('ndim(размерность масива): {0}\nshape(размер каждого измеренеия):\
{1}\nsize(общий размер массива): {2}'.format(x3.ndim, x3.shape, x3.size))

ndim(размерность масива): 3
shape(размер каждого измеренеия):(3, 4, 5)
size(общий размер массива): 60


In [18]:
print('dtype(тип данных): ', x3.dtype)

dtype(тип данных):  int64


In [19]:
print('itemsize:', x3.itemsize, 'bytes')

itemsize: 8 bytes


In [20]:
print('nbytes:', x3.nbytes, 'bytes')

nbytes: 480 bytes


In [21]:
x3.nbytes == x3.itemsize * x3.size

True

In [22]:
# индексация
x1[0]

5

In [23]:
x1[-1]

9

In [24]:
x2

array([[3, 5, 2, 4],
       [7, 6, 8, 8],
       [1, 6, 7, 7]])

In [25]:
x2[1, 1]

6

In [27]:
# изменение значений через индексацию (значение будет приведено к типу данных массива!)
x2[1, 1] = 66.6
x2[1, 1]

66

In [29]:
# срезы
x = np.arange(10)
x

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [30]:
x[:5]

array([0, 1, 2, 3, 4])

In [31]:
x[5:]

array([5, 6, 7, 8, 9])

In [32]:
x[4:7]

array([4, 5, 6])

In [33]:
x[::2]

array([0, 2, 4, 6, 8])

In [34]:
x[1::2]

array([1, 3, 5, 7, 9])

In [35]:
x[::-1]

array([9, 8, 7, 6, 5, 4, 3, 2, 1, 0])

In [36]:
x[5::-2]

array([5, 3, 1])

In [37]:
# многомерные срезы
x2

array([[ 3,  5,  2,  4],
       [ 7, 66,  8,  8],
       [ 1,  6,  7,  7]])

In [38]:
# апо вторую строку и по третий столбец
x2[:2, :3]

array([[ 3,  5,  2],
       [ 7, 66,  8]])

In [39]:
x2[:3, ::2]

array([[3, 2],
       [7, 8],
       [1, 7]])

In [40]:
x2[::-1, ::-1]

array([[ 7,  7,  6,  1],
       [ 8,  8, 66,  7],
       [ 4,  2,  5,  3]])

In [42]:
# доступ к столбцам и строкам массива
# первый столбец
print(x2[:, 0])

[3 7 1]


In [43]:
# первая строка
print(x2[0, :])

[3 5 2 4]


In [44]:
# или более просто для строки
print(x2[0])

[3 5 2 4]


**Важно!** Срезы массивов предоставляются не как копии, а как представления. Это отличие от простых списков в python. Соответственно меняем срез, меняется и массив

In [46]:
x2

array([[ 3,  5,  2,  4],
       [ 7, 66,  8,  8],
       [ 1,  6,  7,  7]])

In [47]:
x2_sub = x2[:2, :2]

In [48]:
x2_sub

array([[ 3,  5],
       [ 7, 66]])

In [49]:
x2_sub[0, 0] = 111
x2_sub

array([[111,   5],
       [  7,  66]])

In [50]:
x2

array([[111,   5,   2,   4],
       [  7,  66,   8,   8],
       [  1,   6,   7,   7]])

In [51]:
# необходимо использовать копирование
x2_sub_copy = x2[:2, :2].copy()

In [53]:
# форма массивов методом reshape(). Метод не изменяет на месте!!!
grid = np.arange(1, 10)
grid

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [56]:
grid.reshape((3, 3))
grid

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [57]:
np.arange(1, 10).reshape((3, 3))

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [66]:
np.reshape(grid, (3, 3))

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [59]:
# второй вариант - через newaxis (на месте)
x = np.array([1, 2, 3])
x

array([1, 2, 3])

In [64]:
np.reshape(x, (3, 1))

array([[1],
       [2],
       [3]])

In [65]:
x[:, np.newaxis]

array([[1],
       [2],
       [3]])

In [70]:
# слияние массивов (можно объединять более двух)
x = np.array([1, 2, 3])
y = np.array([3, 2, 1])
np.concatenate([x, y])

array([1, 2, 3, 3, 2, 1])

In [75]:
# для двумерных массивов
grid = np.array([[1, 2, 3], 
                 [4, 5, 6]])

In [73]:
np.concatenate([grid, grid], axis=0)

array([[1, 2, 3],
       [4, 5, 6],
       [1, 2, 3],
       [4, 5, 6]])

In [74]:
np.concatenate([grid, grid], axis=1)

array([[1, 2, 3, 1, 2, 3],
       [4, 5, 6, 4, 5, 6]])

In [76]:
# объединение по вериткали np.vstack и горизонтали np.hstack
np.vstack([x, grid])

array([[1, 2, 3],
       [1, 2, 3],
       [4, 5, 6]])

In [77]:
z = np.array([[88], 
              [99]])

In [79]:
np.hstack([z, grid])

array([[88,  1,  2,  3],
       [99,  4,  5,  6]])

In [81]:
# разбиение с помощью split, vsplit, hsplit - необходимо передать список индексов с точками раздела
x = np.arange(9)
x1, x2, x3 = np.split(x, (3, 5))

In [82]:
print(x1, x2, x3)

[0 1 2] [3 4] [5 6 7 8]


In [84]:
grid = np.arange(16).reshape((4, 4))
grid

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [85]:
upper, lower = np.split(grid, [2])

In [86]:
print(upper, lower)

[[0 1 2 3]
 [4 5 6 7]] [[ 8  9 10 11]
 [12 13 14 15]]


In [87]:
left, right = np.hsplit(grid, [2])
print(left, right)

[[ 0  1]
 [ 4  5]
 [ 8  9]
 [12 13]] [[ 2  3]
 [ 6  7]
 [10 11]
 [14 15]]


In [88]:
# np.dsplit разделяет по третьей оси