In [1]:
import torch
print(torch.cuda.is_available())
print(torch.rand(2, 2))

True
tensor([[0.2090, 0.9000],
        [0.9363, 0.2597]])


In [3]:
cpu_tensor = torch.rand(2, 2)
cpu_tensor.device

device(type='cpu')

In [4]:
# Прокиним тензор в GPU
gpu_tensor = cpu_tensor.to('cuda')
gpu_tensor.device

device(type='cuda', index=0)

[Документация pytorch](https://pytorch.org/docs/stable/index.html)

[Тензоры в pytorch](https://pytorch.org/docs/stable/index.html)

In [7]:
tens = torch.rand(3, 3)

In [8]:
# максимальный элемент в тензоре
tens.max()

tensor(0.9905)

In [9]:
# значение
tens.max().item()

0.9904642105102539

In [11]:
tens = torch.tensor([[0, 1, 1], [2, 0, 0], [1, 3, 2]])

In [12]:
# изменим тип тензора
tens.type()

'torch.LongTensor'

In [14]:
tens_f = tens.to(dtype=torch.float32)
tens_f.type()

'torch.FloatTensor'

In [17]:
# для inplace методов определены именя, завершающиеся на _
tens = torch.rand(3, 3)
tens.log2()

tensor([[-0.7446, -0.7164, -2.4926],
        [-0.6391, -1.3388, -3.8280],
        [-0.3688, -0.4226, -0.8130]])

In [18]:
tens

tensor([[0.5968, 0.6086, 0.1777],
        [0.6421, 0.3953, 0.0704],
        [0.7744, 0.7461, 0.5692]])

In [19]:
# а теперь на месте
tens.log2_()

tensor([[-0.7446, -0.7164, -2.4926],
        [-0.6391, -1.3388, -3.8280],
        [-0.3688, -0.4226, -0.8130]])

In [20]:
tens

tensor([[-0.7446, -0.7164, -2.4926],
        [-0.6391, -1.3388, -3.8280],
        [-0.3688, -0.4226, -0.8130]])

In [23]:
# измененеие формы представления тензора
flat_tensor = torch.rand(784)
flat_tensor.shape

torch.Size([784])

In [24]:
# отображает flat_tensor в новом виде. Если в flat_tensor внести изменения - изменится и продукт view()
viewed_tensor = flat_tensor.view(1, 28, 28)
viewed_tensor.shape

torch.Size([1, 28, 28])

In [25]:
# тоже самое, но с проверкой смежности после внесенных изменений
reshaped_tensor = flat_tensor.reshape(1, 28, 28)
reshaped_tensor.shape

torch.Size([1, 28, 28])

In [28]:
# изменение рамзера тензора
hwc_tensor = torch.rand(640, 480, 1)
chw_tensor = hwc_tensor.permute(2, 0, 1)
chw_tensor.shape

torch.Size([1, 640, 480])

## Пример классификации изображений

### Предварительная обработка

Класс ImageFolder из torchvision позволяет создать набор данных, при условии, что данные хранятся в структуре, в которой каждый каталог представляет из себя маркировку.

In [34]:
import torchvision
from torchvision import transforms

В данном случае:

- изображения ресайзятся в 64х64 (на самом деле для ускорения вычислений). Как правило считается на 224х224 или 229х229 ну или в зависимости от вычислительных возможностей
- перегоняются в тензор
- нормализуются средним стандартным отклонением ImageNet (для работы с реальнысми данными конечно стоит попробоывать посчитать эти значения непосредственно для дата-сета)

In [40]:
train_data_path = 'pytorch_learning/train/'
transform = transforms.Compose([
    transforms.Resize(64),
    transforms.ToTensor(),
    transforms.Normalize(mean=[0.485, 0.456, 0.406],
                        std=[0.229, 0.234, 0.225])
])
train_data = torchvision.datasets.ImageFolder(root=train_data_path, transform=transform)

### Валидация и контрольные наборы